[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
trust-dns-resolver = "0.23.2"
